# Site settings
title: Phoney Girlfriend
email: phoneygirlfriend@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.phoneygirlfriend.com" # the base hostname & protocol for your site
twitter_username: phoney_girl

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap

excerpt_separator: <!--more-->
